# Generated by Django 5.0.6 on 2026-06-01 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=60, verbose_name='联系人')),
                ('phone', models.CharField(max_length=30, verbose_name='手机号')),
                ('party_size', models.PositiveIntegerField(default=1, verbose_name='报名人数')),
                ('travel_date', models.DateField(verbose_name='出行日期')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='routes.travelroute')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
