# Generated by Django 5.0.6 on 2026-06-01 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('assembly', '集合提醒'), ('weather', '天气提示'), ('packing', '物品清单'), ('change', '行程变更')], max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('publish_at', models.DateTimeField(verbose_name='发布时间')),
                ('is_sent', models.BooleanField(default=False, verbose_name='已发送')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='routes.travelroute')),
            ],
            options={
                'ordering': ['-publish_at', 'id'],
            },
        ),
    ]
