# Generated by Django 5.0.6 on 2026-06-01 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(default=1, verbose_name='第几天')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='当天顺序')),
                ('note', models.CharField(blank=True, max_length=160, verbose_name='安排说明')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.attraction')),
            ],
            options={
                'ordering': ['day', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TravelRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='线路名称')),
                ('city', models.CharField(max_length=50, verbose_name='目的地城市')),
                ('days', models.PositiveIntegerField(default=1, verbose_name='天数')),
                ('transport', models.CharField(max_length=80, verbose_name='交通方式')),
                ('hotel_level', models.CharField(max_length=80, verbose_name='住宿标准')),
                ('min_group_size', models.PositiveIntegerField(default=4, verbose_name='最低成团人数')),
                ('max_group_size', models.PositiveIntegerField(default=20, verbose_name='最多人数')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基础费用')),
                ('guide_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='导游服务费')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('forming', '报名成团中')], default='draft', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='行程简介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attractions', models.ManyToManyField(related_name='routes', through='routes.RouteStop', to='attractions.attraction')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.travelroute'),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'day', 'order')},
        ),
    ]
