# Generated by Django 5.0.6 on 2026-06-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='景点名称')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('category', models.CharField(choices=[('nature', '自然风光'), ('culture', '人文历史'), ('family', '亲子休闲'), ('food', '美食街区')], max_length=20, verbose_name='类型')),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='建议游玩小时')),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='门票价格')),
                ('highlight', models.CharField(max_length=160, verbose_name='亮点')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
